### ISSUE TITLE
http obs output does not include the observatory grade

### ISSUE THREAD

**Issue by claudijd** [caggle/vautomator-standalone#10]
I ran a scan using master and it doesn't include the observatory grade, which I think is one of the more important scan requirements to look at

**Comment by caggle** [comment]
I will see if this is an httpobs client issue, maybe there is a flag I am missing while running it.

**Comment by claudijd** [comment]
Yeah, I mean ultimately, we could have both, but if there's an expectation of manual review then it should have human readable stuff, but if we eventually get to systematic processing, maybe in the service model version, we can do it there and output a processed report (one document that we can review that pulls everything together, maybe even with pre-populated markdown formatting for BMO insertion)

**Comment by caggle** [comment]
This is closed with https://github.com/caggle/vautomator-standalone/pull/12
